apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.appPort }}
    name: {{ .Values.appPortName }}
  type: {{ .Values.type }}
  selector:
    app: {{ .Values.appName }}
